=== IvanPetriv/hmi-lab/myproject/media/data_schemas/blogs.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "author": {
        "type": "string"
      },
      "author_image_url": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "content": {
        "type": "string"
      },
      "datetime": {
        "type": "string",
        "format": "date-time"
      }
    },
    "required": [
      "id",
      "title",
      "author",
      "author_image_url",
      "description",
      "content",
      "datetime"
    ]
  }
}

=== IvanPetriv/hmi-lab/myproject/media/data/blogs.json
[
  {
    "id": "guess-the-elo",
    "title": "GUESS THE ELO #182",
    "author": "Levy Rozman",
    "author_image_url": "../../playground/static/pictures/100720171932.jpg",
    "description": "I officially quit the chess after I’ve seen the most disgusting, the most bizarre and braindead games by my chess followers. I could not believe my eyes when I saw how my subscriber had a mate in 1 but instead they hung a queen. It’s like they won a lottery and just shot their knees off so they can’t walk and claim the money.",
    "content": "I officially quit the chess after I’ve seen the most disgusting, the most bizarre and braindead games by my chess followers. I could not believe my eyes when I saw how my subscriber had a mate in 1 but instead they hung a queen. It’s like they won a lottery and just shot their knees off so they can’t walk and claim the money.\nI officially quit the chess after I’ve seen the most disgusting, the most bizarre and braindead games by my chess followers. I could not believe my eyes when I saw how my subscriber had a mate in 1 but instead they hung a queen. It’s like they won a lottery and just shot their knees off so they can’t walk and claim the money.",
    "datetime": "2025-02-03 18:42:58"
  },
  {
    "id": "wed",
    "title": "GUESS THE ELO #183",
    "author": "Levy Rozman",
    "author_image_url": "static/pictures/100720171932.jpg",
    "description": "I officially quit the chess after I’ve seen the most disgusting, the most bizarre and braindead games by my chess followers. I could not believe my eyes when I saw how my subscriber had a mate in 1 but instead they hung a queen. It’s like they won a lottery and just shot their knees off so they can’t walk and claim the money.",
    "content": "...",
    "datetime": "2025-02-03 18:42:58"
  }
]
